#ifndef AURORA_ERR_H
#define AURORA_ERR_H
#ifdef __cplusplus
extern "C"
{
#endif

	typedef enum AURORA_FS_ERR
	{
		AURORA_FS_ERR_OK = 0,
		AURORA_FS_ERR_FAILURE = -1,
		AURORA_FS_ERR_INVALID_ARGUMENT = -2,
		AURORA_FS_ERR_NULL_POINTER = -3,
		AURORA_FS_ERR_OUT_OF_RANGE = -4,
		AURORA_FS_ERR_NOT_INITIALIZED = -5,
		AURORA_FS_ERR_ALREADY_INITIALIZED = -6,
		AURORA_FS_ERR_NOT_SUPPORTED = -7,
		AURORA_FS_ERR_NO_MEMORY = -8,
		AURORA_FS_ERR_OVERFLOW = -9,
		AURORA_FS_ERR_UNDERFLOW = -10,
		AURORA_FS_ERR_BUFFER_TOO_SMALL = -11,
		AURORA_FS_ERR_TIMEOUT = -12,
		AURORA_FS_ERR_CANCELLED = -13,
		AURORA_FS_ERR_BUSY = -14,
		AURORA_FS_ERR_IO = -20,
		AURORA_FS_ERR_NOT_FOUND = -21,
		AURORA_FS_ERR_ALREADY_EXISTS = -22,
		AURORA_FS_ERR_PERMISSION_DENIED = -23,
		AURORA_FS_ERR_PATH_TOO_LONG = -24,
		AURORA_FS_ERR_INVALID_PATH = -25,
		AURORA_FS_ERR_IS_DIRECTORY = -26,
		AURORA_FS_ERR_NOT_DIRECTORY = -27,
		AURORA_FS_ERR_READ_ONLY = -28,
		AURORA_FS_ERR_BROKEN_PIPE = -29,
		AURORA_FS_ERR_OPEN_FAILED = -30,
		AURORA_FS_ERR_READ_FAILED = -31,
		AURORA_FS_ERR_WRITE_FAILED = -32,
		AURORA_FS_ERR_SEEK_FAILED = -33,
		AURORA_FS_ERR_CLOSE_FAILED = -34,
		AURORA_FS_ERR_SYNC_FAILED = -35,
		AURORA_FS_ERR_UNKNOWN = -100,
	} aurora_fs_err_t;

#ifdef __cplusplus
}
#endif
#endif